#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka1:2001/eureka
#    register-with-eureka: true
#    registry-fetch-interval-seconds: 30

spring:
  application:    name: item-service

#server:
#  port: 8001

  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka


management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh
        
---
spring:
  profiles: item1
  rabbitmq:
    address: 192.168.71.13
    port: 5672
    username: admin
    password: admin
  
server:
  port: 8001
---
spring:
  profiles: item2
  rabbitmq:
    address: 192.168.71.13
    port: 5672
    username: admin
    password: admin

server:
  port: 8002