eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
    register-with-eureka: true
    registry-fetch-interval-seconds: 30

spring:
  application:
    name: order-service

#server:
#  port: 8201

feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  rabbitmq:
    host: 192.168.71.13
    port: 5672
    username: admin
    password: admin
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  rabbitmq:
    addresses: 192.168.71.13
    port: 5672
    username: admin
    password: admin
  
server:
  port: 8202